[package]
name = "audio_preprocessor"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
rayon = "1.10"
walkdir = "2.5"

[build-dependencies]
bindgen = "0.70"
pkg-config = "0.3"

[profile.release]
opt-level = 3
lto = true
